# Generated by Django 5.2.8 on 2025-11-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='languages',
            field=models.TextField(default='Не выбрано', verbose_name='Языки'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='place',
            field=models.TextField(default='Не выбрано', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.FloatField(verbose_name='Цена($)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='price',
            field=models.FloatField(verbose_name='Цена($)'),
        ),
    ]
