# Generated by Django 5.2.8 on 2025-11-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0002_vacancy_languages_vacancy_place_alter_tariff_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='place',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='languages',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='places',
            field=models.ManyToManyField(to='iprovider.place', verbose_name='Места'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='languages',
            field=models.ManyToManyField(to='iprovider.language', verbose_name='Языки'),
        ),
    ]
