# Generated by Django 5.2.8 on 2025-11-16 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0003_language_place_remove_vacancy_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Страна')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Код страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iprovider.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='countries',
            field=models.ManyToManyField(blank=True, to='iprovider.country', verbose_name='Страны'),
        ),
    ]
