# Generated by Django 5.2.8 on 2025-11-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0004_country_place_address_place_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.TextField(default='Неизвестный адрес', unique=True, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
