# Generated by Django 5.2.8 on 2025-11-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0005_remove_place_name_alter_place_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.TextField(default='Неизвестный адрес', unique=True, verbose_name='Адрес'),
        ),
    ]
