# Generated by Django 5.2.8 on 2025-11-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0007_place_name_alter_place_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
    ]
