# Generated by Django 5.2.8 on 2025-11-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0008_remove_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
