# Generated by Django 5.2.8 on 2025-11-20 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0010_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.FloatField(verbose_name='Базовая цена($)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='price',
            field=models.FloatField(verbose_name='Базовая цена($)'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iprovider.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iprovider.city', verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='TariffPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Цена($)')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iprovider.city', verbose_name='Город')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iprovider.country', verbose_name='Страна')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='iprovider.tariff')),
            ],
            options={
                'verbose_name': 'Цена тарифа',
                'verbose_name_plural': 'Цены тарифов',
                'unique_together': {('tariff', 'city'), ('tariff', 'country')},
            },
        ),
    ]
