# Generated by Django 6.0 on 2025-12-25 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0013_alter_tariff_options_tariff_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffprice',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_prices', to='iprovider.tariff'),
        ),
        migrations.CreateModel(
            name='Packets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование пакета')),
                ('price', models.FloatField(verbose_name='Базовая цена($)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('watched', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('description', models.TextField(default='Здесь скоро будет описание', verbose_name='Описание пакета')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets_categories', to='iprovider.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Пакет',
                'verbose_name_plural': 'Пакеты',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Separately',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование отдельного компонента')),
                ('price', models.FloatField(verbose_name='Базовая цена($)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('watched', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('description', models.TextField(default='Здесь скоро будет описание', verbose_name='Описание отдельного компонента')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separately_categories', to='iprovider.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Отдельный компонент',
                'verbose_name_plural': 'Отдельные компоненты',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PacketsPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Цена($)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iprovider.city', verbose_name='Город')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iprovider.country', verbose_name='Страна')),
                ('packets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets_prices', to='iprovider.packets')),
            ],
            options={
                'verbose_name': 'Цена пакета',
                'verbose_name_plural': 'Цены пакетов',
                'unique_together': {('packets', 'city'), ('packets', 'country')},
            },
        ),
        migrations.CreateModel(
            name='SeparatelyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Цена($)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iprovider.city', verbose_name='Город')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iprovider.country', verbose_name='Страна')),
                ('separately', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separately_prices', to='iprovider.separately')),
            ],
            options={
                'verbose_name': 'Цена отдельного компонента',
                'verbose_name_plural': 'Цены отдельных компонентов',
                'unique_together': {('separately', 'city'), ('separately', 'country')},
            },
        ),
    ]
