# Generated by Django 6.0 on 2026-01-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0014_alter_tariffprice_tariff_packets_separately_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packets',
            name='details_html',
            field=models.TextField(blank=True, help_text='Полное описание с HTML разметкой. Будет отображаться как есть.', verbose_name='Детальное описание (HTML)'),
        ),
        migrations.AddField(
            model_name='packets',
            name='features_json',
            field=models.JSONField(blank=True, default=list, help_text='Список характеристик в формате JSON', verbose_name='Характеристики (JSON)'),
        ),
        migrations.AddField(
            model_name='packets',
            name='features_text',
            field=models.TextField(blank=True, help_text='Характеристики, каждая с новой строки. Для отображения в виде списка.', verbose_name='Характеристики (текст)'),
        ),
        migrations.AddField(
            model_name='separately',
            name='details_html',
            field=models.TextField(blank=True, help_text='Полное описание с HTML разметкой. Будет отображаться как есть.', verbose_name='Детальное описание (HTML)'),
        ),
        migrations.AddField(
            model_name='separately',
            name='features_json',
            field=models.JSONField(blank=True, default=list, help_text='Список характеристик в формате JSON. Например: ["3 simultaneous connections", "Servers in 10 countries"]', verbose_name='Характеристики (JSON)'),
        ),
        migrations.AddField(
            model_name='separately',
            name='features_text',
            field=models.TextField(blank=True, help_text='Характеристики, каждая с новой строки. Для отображения в виде списка.', verbose_name='Характеристики (текст)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='details_html',
            field=models.TextField(blank=True, help_text='Полное описание с HTML разметкой. Будет отображаться как есть.', verbose_name='Детальное описание (HTML)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='features_json',
            field=models.JSONField(blank=True, default=list, help_text='Список характеристик в формате JSON. Например: ["Скорость: 100 Mbps", "Трафик: 15 GB"]', verbose_name='Характеристики (JSON)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='features_text',
            field=models.TextField(blank=True, help_text='Характеристики, каждая с новой строки. Для отображения в виде списка.', verbose_name='Характеристики (текст)'),
        ),
    ]
