# Generated by Django 6.0 on 2026-01-03 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0015_packets_details_html_packets_features_json_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packets',
            name='details_html',
        ),
        migrations.RemoveField(
            model_name='packets',
            name='features_json',
        ),
        migrations.RemoveField(
            model_name='separately',
            name='details_html',
        ),
        migrations.RemoveField(
            model_name='separately',
            name='features_json',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='details_html',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='features_json',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('packets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packets_ratings', to='iprovider.packets')),
                ('separately', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='separately_ratings', to='iprovider.separately')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_ratings', to='iprovider.tariff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'unique_together': {('user', 'packets'), ('user', 'separately'), ('user', 'tariff')},
            },
        ),
    ]
