# Generated by Django 6.0 on 2026-01-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0016_remove_packets_details_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название места'),
        ),
    ]
