# Generated by Django 6.0.2 on 2026-02-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0018_alter_place_options_vacancy_features_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cities',
            field=models.ManyToManyField(blank=True, help_text='Новость будет показана только в этих городах (даже если страна уже выбрана', to='iprovider.city', verbose_name='Города'),
        ),
        migrations.AddField(
            model_name='news',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text='Новость будет показана во всех выбранных странах', to='iprovider.country', verbose_name='Страны'),
        ),
    ]
