# Generated by Django 6.0.2 on 2026-02-12 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0019_news_cities_news_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='places',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='countries',
            field=models.ManyToManyField(blank=True, editable=False, to='iprovider.country', verbose_name='Страны'),
        ),
        migrations.CreateModel(
            name='VacancyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.ManyToManyField(to='iprovider.language', verbose_name='Требуемые языки')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iprovider.place', verbose_name='Офис')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='iprovider.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Офис для вакансии',
                'verbose_name_plural': 'Офисы для вакансии',
                'unique_together': {('vacancy', 'place')},
            },
        ),
    ]
