# Generated by Django 6.0.2 on 2026-02-12 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0020_remove_vacancy_languages_remove_vacancy_places_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(default='Здесь скоро будет описание', verbose_name='Описание акции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='stocks_photos/')),
                ('watched', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='iprovider.category', verbose_name='Категория')),
                ('cities', models.ManyToManyField(blank=True, help_text='Акция будет показана только в этих городах (даже если страна уже выбрана', to='iprovider.city', verbose_name='Города')),
                ('countries', models.ManyToManyField(blank=True, help_text='Акция будет показана во всех выбранных странах', to='iprovider.country', verbose_name='Страны')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['-created_at'],
            },
        ),
    ]
