# Generated by Django 6.0.2 on 2026-02-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0021_stocks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'country')},
        ),
        migrations.AddField(
            model_name='category',
            name='title_de',
            field=models.CharField(max_length=150, null=True, verbose_name='Наименование категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Наименование категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_nl',
            field=models.CharField(max_length=150, null=True, verbose_name='Наименование категории'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_de',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_de',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_de',
            field=models.TextField(default='Здесь скоро будет описание', null=True, verbose_name='Описание новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(default='Здесь скоро будет описание', null=True, verbose_name='Описание новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_nl',
            field=models.TextField(default='Здесь скоро будет описание', null=True, verbose_name='Описание новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='packets',
            name='description_de',
            field=models.TextField(default='Здесь скоро будет описание', null=True, verbose_name='Описание пакета'),
        ),
        migrations.AddField(
            model_name='packets',
            name='description_en',
            field=models.TextField(default='Здесь скоро будет описание', null=True, verbose_name='Описание пакета'),
        ),
        migrations.AddField(
            model_name='packets',
            name='description_nl',
            field=models.TextField(default='Здесь скоро будет описание', null=True, verbose_name='Описание пакета'),
        ),
        migrations.AddField(
            model_name='packets',
            name='features_text_de',
            field=models.TextField(blank=True, help_text='Характеристики, каждая с новой строки. Для отображения в виде списка.', null=True, verbose_name='Характеристики (текст)'),
        ),
        migrations.AddField(
            model_name='packets',
            name='features_text_en',
            field=models.TextField(blank=True, help_text='Характеристики, каждая с новой строки. Для отображения в виде списка.', null=True, verbose_name='Характеристики (текст)'),
        ),
        migrations.AddField(
            model_name='packets',
            name='features_text_nl',
            field=models.TextField(blank=True, help_text='Характеристики, каждая с новой строки. Для отображения в виде списка.', null=True, verbose_name='Характеристики (текст)'),
        ),
        migrations.AddField(
            model_name='packets',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование пакета'),
        ),
        migrations.AddField(
            model_name='packets',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование пакета'),
        ),
        migrations.AddField(
            model_name='packets',
            name='title_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование пакета'),
        ),
        migrations.AddField(
            model_name='place',
            name='address_de',
            field=models.TextField(blank=True, null=True, verbose_name='Полный адрес'),
        ),
        migrations.AddField(
            model_name='place',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='Полный адрес'),
        ),
        migrations.AddField(
            model_name='place',
            name='address_nl',
            field=models.TextField(blank=True, null=True, verbose_name='Полный адрес'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_nl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='separately',
            name='description_de',
            field=models.TextField(default='Здесь скоро будет описание', null=True, verbose_name='Описание отдельного компонента'),
        ),
        migrations.AddField(
            model_name='separately',
            name='description_en',
            field=models.TextField(default='Здесь скоро будет описание', null=True, verbose_name='Описание отдельного компонента'),
        ),
        migrations.AddField(
            model_name='separately',
            name='description_nl',
            field=models.TextField(default='Здесь скоро будет описание', null=True, verbose_name='Описание отдельного компонента'),
        ),
        migrations.AddField(
            model_name='separately',
            name='features_text_de',
            field=models.TextField(blank=True, help_text='Характеристики, каждая с новой строки. Для отображения в виде списка.', null=True, verbose_name='Характеристики (текст)'),
        ),
        migrations.AddField(
            model_name='separately',
            name='features_text_en',
            field=models.TextField(blank=True, help_text='Характеристики, каждая с новой строки. Для отображения в виде списка.', null=True, verbose_name='Характеристики (текст)'),
        ),
        migrations.AddField(
            model_name='separately',
            name='features_text_nl',
            field=models.TextField(blank=True, help_text='Характеристики, каждая с новой строки. Для отображения в виде списка.', null=True, verbose_name='Характеристики (текст)'),
        ),
        migrations.AddField(
            model_name='separately',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование отдельного компонента'),
        ),
        migrations.AddField(
            model_name='separately',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование отдельного компонента'),
        ),
        migrations.AddField(
            model_name='separately',
            name='title_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование отдельного компонента'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='description_de',
            field=models.TextField(default='Здесь скоро будет описание', null=True, verbose_name='Описание акции'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='description_en',
            field=models.TextField(default='Здесь скоро будет описание', null=True, verbose_name='Описание акции'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='description_nl',
            field=models.TextField(default='Здесь скоро будет описание', null=True, verbose_name='Описание акции'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='title_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='description_de',
            field=models.TextField(default='Здесь скоро будет описание', null=True, verbose_name='Описание тарифа'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='description_en',
            field=models.TextField(default='Здесь скоро будет описание', null=True, verbose_name='Описание тарифа'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='description_nl',
            field=models.TextField(default='Здесь скоро будет описание', null=True, verbose_name='Описание тарифа'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='features_text_de',
            field=models.TextField(blank=True, help_text='Характеристики, каждая с новой строки. Для отображения в виде списка.', null=True, verbose_name='Характеристики (текст)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='features_text_en',
            field=models.TextField(blank=True, help_text='Характеристики, каждая с новой строки. Для отображения в виде списка.', null=True, verbose_name='Характеристики (текст)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='features_text_nl',
            field=models.TextField(blank=True, help_text='Характеристики, каждая с новой строки. Для отображения в виде списка.', null=True, verbose_name='Характеристики (текст)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование тарифа'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование тарифа'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='title_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование тарифа'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_de',
            field=models.TextField(default='Здесь скоро будет описание', null=True, verbose_name='Описание вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_en',
            field=models.TextField(default='Здесь скоро будет описание', null=True, verbose_name='Описание вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_nl',
            field=models.TextField(default='Здесь скоро будет описание', null=True, verbose_name='Описание вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='features_text_de',
            field=models.TextField(blank=True, help_text='Характеристики, каждая с новой строки. Для отображения в виде списка.', null=True, verbose_name='Характеристики (текст)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='features_text_en',
            field=models.TextField(blank=True, help_text='Характеристики, каждая с новой строки. Для отображения в виде списка.', null=True, verbose_name='Характеристики (текст)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='features_text_nl',
            field=models.TextField(blank=True, help_text='Характеристики, каждая с новой строки. Для отображения в виде списка.', null=True, verbose_name='Характеристики (текст)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование вакансии'),
        ),
        migrations.AlterField(
            model_name='news',
            name='cities',
            field=models.ManyToManyField(blank=True, help_text='Новость будет показана только в этих городах (даже если страна уже выбрана)', to='iprovider.city', verbose_name='Города'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='cities',
            field=models.ManyToManyField(blank=True, help_text='Акция будет показана только в этих городах (даже если страна уже выбрана)', to='iprovider.city', verbose_name='Города'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'country'), ('name_de', 'country'), ('name_en', 'country'), ('name_nl', 'country')},
        ),
    ]
