# Generated by Django 6.0.2 on 2026-02-20 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0022_alter_city_unique_together_category_title_de_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='packets',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Packet', 'verbose_name_plural': 'Packets'},
        ),
        migrations.AlterModelOptions(
            name='packetsprice',
            options={'verbose_name': 'Packet price', 'verbose_name_plural': 'Packet prices'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Office', 'verbose_name_plural': 'Offices'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterModelOptions(
            name='separately',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Separate service', 'verbose_name_plural': 'Separate services'},
        ),
        migrations.AlterModelOptions(
            name='separatelyprice',
            options={'verbose_name': 'Separate service price', 'verbose_name_plural': 'Separate service prices'},
        ),
        migrations.AlterModelOptions(
            name='stocks',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Tariff', 'verbose_name_plural': 'Tariffs'},
        ),
        migrations.AlterModelOptions(
            name='tariffprice',
            options={'verbose_name': 'Tariff price', 'verbose_name_plural': 'Tariff prices'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AlterModelOptions(
            name='vacancylocation',
            options={'verbose_name': 'Vacancy office', 'verbose_name_plural': 'Vacancy offices'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='iprovider.category', verbose_name='Parent category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_de',
            field=models.CharField(max_length=150, null=True, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_nl',
            field=models.CharField(max_length=150, null=True, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iprovider.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Country code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_de',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name_de',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='iprovider.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='news',
            name='cities',
            field=models.ManyToManyField(blank=True, help_text='News will be shown only in these cities (even if country is selected)', to='iprovider.city', verbose_name='Cities'),
        ),
        migrations.AlterField(
            model_name='news',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text='News will be shown in all selected countries', to='iprovider.country', verbose_name='Countries'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(default='Description will be here soon', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_de',
            field=models.TextField(default='Description will be here soon', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_en',
            field=models.TextField(default='Description will be here soon', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_nl',
            field=models.TextField(default='Description will be here soon', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='news',
            name='watched',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='packets',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets_categories', to='iprovider.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='packets',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='packets',
            name='description',
            field=models.TextField(default='Description will be here soon', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='packets',
            name='description_de',
            field=models.TextField(default='Description will be here soon', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='packets',
            name='description_en',
            field=models.TextField(default='Description will be here soon', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='packets',
            name='description_nl',
            field=models.TextField(default='Description will be here soon', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='packets',
            name='features_text',
            field=models.TextField(blank=True, help_text='Each feature on a new line. Will be displayed as a list.', verbose_name='Features (text)'),
        ),
        migrations.AlterField(
            model_name='packets',
            name='features_text_de',
            field=models.TextField(blank=True, help_text='Each feature on a new line. Will be displayed as a list.', null=True, verbose_name='Features (text)'),
        ),
        migrations.AlterField(
            model_name='packets',
            name='features_text_en',
            field=models.TextField(blank=True, help_text='Each feature on a new line. Will be displayed as a list.', null=True, verbose_name='Features (text)'),
        ),
        migrations.AlterField(
            model_name='packets',
            name='features_text_nl',
            field=models.TextField(blank=True, help_text='Each feature on a new line. Will be displayed as a list.', null=True, verbose_name='Features (text)'),
        ),
        migrations.AlterField(
            model_name='packets',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='packets',
            name='price',
            field=models.FloatField(verbose_name='Base price ($)'),
        ),
        migrations.AlterField(
            model_name='packets',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Packet name'),
        ),
        migrations.AlterField(
            model_name='packets',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Packet name'),
        ),
        migrations.AlterField(
            model_name='packets',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Packet name'),
        ),
        migrations.AlterField(
            model_name='packets',
            name='title_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Packet name'),
        ),
        migrations.AlterField(
            model_name='packets',
            name='watched',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='packetsprice',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iprovider.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='packetsprice',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iprovider.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='packetsprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='packetsprice',
            name='price',
            field=models.FloatField(verbose_name='Price ($)'),
        ),
        migrations.AlterField(
            model_name='packetsprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Full address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address_de',
            field=models.TextField(blank=True, null=True, verbose_name='Full address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='Full address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address_nl',
            field=models.TextField(blank=True, null=True, verbose_name='Full address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iprovider.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='place',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iprovider.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name_nl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place name'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='separately',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separately_categories', to='iprovider.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='separately',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='separately',
            name='description',
            field=models.TextField(default='Description will be here soon', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='separately',
            name='description_de',
            field=models.TextField(default='Description will be here soon', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='separately',
            name='description_en',
            field=models.TextField(default='Description will be here soon', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='separately',
            name='description_nl',
            field=models.TextField(default='Description will be here soon', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='separately',
            name='features_text',
            field=models.TextField(blank=True, help_text='Each feature on a new line. Will be displayed as a list.', verbose_name='Features (text)'),
        ),
        migrations.AlterField(
            model_name='separately',
            name='features_text_de',
            field=models.TextField(blank=True, help_text='Each feature on a new line. Will be displayed as a list.', null=True, verbose_name='Features (text)'),
        ),
        migrations.AlterField(
            model_name='separately',
            name='features_text_en',
            field=models.TextField(blank=True, help_text='Each feature on a new line. Will be displayed as a list.', null=True, verbose_name='Features (text)'),
        ),
        migrations.AlterField(
            model_name='separately',
            name='features_text_nl',
            field=models.TextField(blank=True, help_text='Each feature on a new line. Will be displayed as a list.', null=True, verbose_name='Features (text)'),
        ),
        migrations.AlterField(
            model_name='separately',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='separately',
            name='price',
            field=models.FloatField(verbose_name='Base price ($)'),
        ),
        migrations.AlterField(
            model_name='separately',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Separate service name'),
        ),
        migrations.AlterField(
            model_name='separately',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Separate service name'),
        ),
        migrations.AlterField(
            model_name='separately',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Separate service name'),
        ),
        migrations.AlterField(
            model_name='separately',
            name='title_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Separate service name'),
        ),
        migrations.AlterField(
            model_name='separately',
            name='watched',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='separatelyprice',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iprovider.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='separatelyprice',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iprovider.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='separatelyprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='separatelyprice',
            name='price',
            field=models.FloatField(verbose_name='Price ($)'),
        ),
        migrations.AlterField(
            model_name='separatelyprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='iprovider.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='cities',
            field=models.ManyToManyField(blank=True, help_text='Stock will be shown only in these cities (even if country is selected)', to='iprovider.city', verbose_name='Cities'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text='Stock will be shown in all selected countries', to='iprovider.country', verbose_name='Countries'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='description',
            field=models.TextField(default='Description will be here soon', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='description_de',
            field=models.TextField(default='Description will be here soon', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='description_en',
            field=models.TextField(default='Description will be here soon', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='description_nl',
            field=models.TextField(default='Description will be here soon', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='title_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='watched',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_categories', to='iprovider.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='description',
            field=models.TextField(default='Description will be here soon', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='description_de',
            field=models.TextField(default='Description will be here soon', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='description_en',
            field=models.TextField(default='Description will be here soon', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='description_nl',
            field=models.TextField(default='Description will be here soon', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='features_text',
            field=models.TextField(blank=True, help_text='Each feature on a new line. Will be displayed as a list.', verbose_name='Features (text)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='features_text_de',
            field=models.TextField(blank=True, help_text='Each feature on a new line. Will be displayed as a list.', null=True, verbose_name='Features (text)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='features_text_en',
            field=models.TextField(blank=True, help_text='Each feature on a new line. Will be displayed as a list.', null=True, verbose_name='Features (text)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='features_text_nl',
            field=models.TextField(blank=True, help_text='Each feature on a new line. Will be displayed as a list.', null=True, verbose_name='Features (text)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.FloatField(verbose_name='Base price ($)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tariff name'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Tariff name'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Tariff name'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='title_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Tariff name'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='watched',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='tariffprice',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iprovider.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='tariffprice',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iprovider.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='tariffprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='tariffprice',
            name='price',
            field=models.FloatField(verbose_name='Price ($)'),
        ),
        migrations.AlterField(
            model_name='tariffprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to='iprovider.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='countries',
            field=models.ManyToManyField(blank=True, editable=False, to='iprovider.country', verbose_name='Countries'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(default='Description will be here soon', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description_de',
            field=models.TextField(default='Description will be here soon', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description_en',
            field=models.TextField(default='Description will be here soon', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description_nl',
            field=models.TextField(default='Description will be here soon', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='features_text',
            field=models.TextField(blank=True, help_text='Each feature on a new line. Will be displayed as a list.', verbose_name='Features (text)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='features_text_de',
            field=models.TextField(blank=True, help_text='Each feature on a new line. Will be displayed as a list.', null=True, verbose_name='Features (text)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='features_text_en',
            field=models.TextField(blank=True, help_text='Each feature on a new line. Will be displayed as a list.', null=True, verbose_name='Features (text)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='features_text_nl',
            field=models.TextField(blank=True, help_text='Each feature on a new line. Will be displayed as a list.', null=True, verbose_name='Features (text)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='price',
            field=models.FloatField(verbose_name='Base price ($)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Vacancy title'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Vacancy title'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Vacancy title'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Vacancy title'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='watched',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='vacancylocation',
            name='languages',
            field=models.ManyToManyField(to='iprovider.language', verbose_name='Required languages'),
        ),
        migrations.AlterField(
            model_name='vacancylocation',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iprovider.place', verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='vacancylocation',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='iprovider.vacancy', verbose_name='Vacancy'),
        ),
    ]
