# Generated by Django 6.0.2 on 2026-02-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0023_alter_category_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='details_html',
            field=models.TextField(blank=True, help_text='Use HTML tags for formatting (e.g., <ul>, <li>, <strong>.', verbose_name='Derailed description(HTML)'),
        ),
    ]
