# Generated by Django 6.0.2 on 2026-02-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0027_connectionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='details_html',
            field=models.TextField(blank=True, help_text='Use HTML tags for formatting (e.g., <ul>, <li>, <strong>.)', verbose_name='Detailed description(HTML)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='details_html_de',
            field=models.TextField(blank=True, help_text='Use HTML tags for formatting (e.g., <ul>, <li>, <strong>.)', null=True, verbose_name='Detailed description(HTML)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='details_html_en',
            field=models.TextField(blank=True, help_text='Use HTML tags for formatting (e.g., <ul>, <li>, <strong>.)', null=True, verbose_name='Detailed description(HTML)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='details_html_nl',
            field=models.TextField(blank=True, help_text='Use HTML tags for formatting (e.g., <ul>, <li>, <strong>.)', null=True, verbose_name='Detailed description(HTML)'),
        ),
    ]
