# Generated by Django 6.0.2 on 2026-02-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0029_alter_city_unique_together_remove_category_title_de_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, unique=True, verbose_name='Currency Code')),
                ('rate_to_usd', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Rate to USD')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency Rate',
                'verbose_name_plural': 'Currency Rates',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('payment', 'Payment'), ('refund', 'Refund')], default='payment', max_length=10),
        ),
    ]
