# Generated by Django 6.0.2 on 2026-02-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0030_currencyrate_payment_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_contact_methods',
            field=models.JSONField(default=list, verbose_name='Preferred contact methods'),
        ),
    ]
