# Generated by Django 6.0.2 on 2026-02-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0031_profile_preferred_contact_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Customer ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Payment Method ID'),
        ),
    ]
