# Generated by Django 6.0.2 on 2026-03-01 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('iprovider', '0033_phonenumber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='subscription',
        ),
        migrations.CreateModel(
            name='UserSubcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('tariff', 'Tariff'), ('separately', 'Separate service'), ('packet', 'Packet'), ('vacancy', 'Vacancy')], max_length=20, verbose_name='Subscription type')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End date')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Auto renew')),
                ('price_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Admin notes')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iprovider.city')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iprovider.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User subscription',
                'verbose_name_plural': 'User subscriptions',
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'content_type', 'object_id'), name='unique_active_subscription_per_object')],
            },
        ),
    ]
