# Generated by Django 6.0.2 on 2026-03-02 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0035_usersubscription_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usersubscription',
            name='unique_active_subscription_per_object',
        ),
        migrations.AlterModelOptions(
            name='connectionrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Connection Request', 'verbose_name_plural': 'Connection Requests'},
        ),
        migrations.RemoveField(
            model_name='connectionrequest',
            name='contact_value',
        ),
        migrations.RemoveField(
            model_name='connectionrequest',
            name='preferred_time',
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iprovider.city'),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted to Subscription')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Auto-filled when converted to subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, to='iprovider.subscription', verbose_name='Related Subscription'),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='contact_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
