# Generated by Django 6.0.2 on 2026-03-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0036_remove_usersubscription_unique_active_subscription_per_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='contact_method',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
