# Generated by Django 6.0.3 on 2026-03-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0038_auto_20260302_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stripe_payment_method_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('yookassa', 'ЮKassa'), ('robokassa', 'Robokassa'), ('paypal', 'PayPal'), ('mock', 'Mock (development)')], max_length=20),
        ),
    ]
