# Generated by Django 6.0.3 on 2026-03-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0039_remove_profile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='Currency code'),
        ),
    ]
