# Generated by Django 6.0.3 on 2026-03-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0041_faq_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_de',
            field=models.CharField(blank=True, max_length=150, verbose_name='Title (DE)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Title (EN)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_nl',
            field=models.CharField(blank=True, max_length=150, verbose_name='Title (NL)'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_de',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (DE)'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (EN)'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_nl',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (NL)'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_de',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (DE)'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (EN)'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_nl',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (NL)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_de',
            field=models.TextField(blank=True, default='', verbose_name='Answer (DE)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(blank=True, default='', verbose_name='Answer (EN)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_nl',
            field=models.TextField(blank=True, default='', verbose_name='Answer (NL)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_de',
            field=models.CharField(blank=True, max_length=255, verbose_name='Question (DE)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Question (EN)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_nl',
            field=models.CharField(blank=True, max_length=255, verbose_name='Question (NL)'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_de',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (DE)'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (EN)'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_nl',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (NL)'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_de',
            field=models.TextField(blank=True, default='', verbose_name='Description (DE)'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_nl',
            field=models.TextField(blank=True, default='', verbose_name='Description (NL)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_de',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (DE)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (EN)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_nl',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (NL)'),
        ),
        migrations.AddField(
            model_name='packets',
            name='description_de',
            field=models.TextField(blank=True, default='', verbose_name='Description (DE)'),
        ),
        migrations.AddField(
            model_name='packets',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='packets',
            name='description_nl',
            field=models.TextField(blank=True, default='', verbose_name='Description (NL)'),
        ),
        migrations.AddField(
            model_name='packets',
            name='features_text_de',
            field=models.TextField(blank=True, default='', verbose_name='Features (DE)'),
        ),
        migrations.AddField(
            model_name='packets',
            name='features_text_en',
            field=models.TextField(blank=True, default='', verbose_name='Features (EN)'),
        ),
        migrations.AddField(
            model_name='packets',
            name='features_text_nl',
            field=models.TextField(blank=True, default='', verbose_name='Features (NL)'),
        ),
        migrations.AddField(
            model_name='packets',
            name='title_de',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (DE)'),
        ),
        migrations.AddField(
            model_name='packets',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (EN)'),
        ),
        migrations.AddField(
            model_name='packets',
            name='title_nl',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (NL)'),
        ),
        migrations.AddField(
            model_name='place',
            name='address_de',
            field=models.TextField(blank=True, verbose_name='Address (DE)'),
        ),
        migrations.AddField(
            model_name='place',
            name='address_en',
            field=models.TextField(blank=True, verbose_name='Address (EN)'),
        ),
        migrations.AddField(
            model_name='place',
            name='address_nl',
            field=models.TextField(blank=True, verbose_name='Address (NL)'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_de',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name (DE)'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name (EN)'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_nl',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name (NL)'),
        ),
        migrations.AddField(
            model_name='separately',
            name='description_de',
            field=models.TextField(blank=True, default='', verbose_name='Description (DE)'),
        ),
        migrations.AddField(
            model_name='separately',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='separately',
            name='description_nl',
            field=models.TextField(blank=True, default='', verbose_name='Description (NL)'),
        ),
        migrations.AddField(
            model_name='separately',
            name='features_text_de',
            field=models.TextField(blank=True, default='', verbose_name='Features (DE)'),
        ),
        migrations.AddField(
            model_name='separately',
            name='features_text_en',
            field=models.TextField(blank=True, default='', verbose_name='Features (EN)'),
        ),
        migrations.AddField(
            model_name='separately',
            name='features_text_nl',
            field=models.TextField(blank=True, default='', verbose_name='Features (NL)'),
        ),
        migrations.AddField(
            model_name='separately',
            name='title_de',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (DE)'),
        ),
        migrations.AddField(
            model_name='separately',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (EN)'),
        ),
        migrations.AddField(
            model_name='separately',
            name='title_nl',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (NL)'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='description_de',
            field=models.TextField(blank=True, default='', verbose_name='Description (DE)'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='description_nl',
            field=models.TextField(blank=True, default='', verbose_name='Description (NL)'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='title_de',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (DE)'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (EN)'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='title_nl',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (NL)'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='message_de',
            field=models.TextField(blank=True, default='', verbose_name='Message (DE)'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='message_en',
            field=models.TextField(blank=True, default='', verbose_name='Message (EN)'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='message_nl',
            field=models.TextField(blank=True, default='', verbose_name='Message (NL)'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='subject_de',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subject (DE)'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='subject_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subject (EN)'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='subject_nl',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subject (NL)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='description_de',
            field=models.TextField(blank=True, default='', verbose_name='Description (DE)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='description_nl',
            field=models.TextField(blank=True, default='', verbose_name='Description (NL)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='features_text_de',
            field=models.TextField(blank=True, default='', verbose_name='Features (DE)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='features_text_en',
            field=models.TextField(blank=True, default='', verbose_name='Features (EN)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='features_text_nl',
            field=models.TextField(blank=True, default='', verbose_name='Features (NL)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='title_de',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (DE)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (EN)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='title_nl',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (NL)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_de',
            field=models.TextField(blank=True, default='', verbose_name='Description (DE)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_nl',
            field=models.TextField(blank=True, default='', verbose_name='Description (NL)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='details_html_de',
            field=models.TextField(blank=True, default='', verbose_name='Details HTML (DE)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='details_html_en',
            field=models.TextField(blank=True, default='', verbose_name='Details HTML (EN)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='details_html_nl',
            field=models.TextField(blank=True, default='', verbose_name='Details HTML (NL)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='features_text_de',
            field=models.TextField(blank=True, default='', verbose_name='Features (DE)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='features_text_en',
            field=models.TextField(blank=True, default='', verbose_name='Features (EN)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='features_text_nl',
            field=models.TextField(blank=True, default='', verbose_name='Features (NL)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_de',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (DE)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (EN)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_nl',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (NL)'),
        ),
    ]
