# Generated by Django 6.0.3 on 2026-03-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0042_category_title_de_category_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, verbose_name='Title (RU)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uk',
            field=models.CharField(blank=True, max_length=150, verbose_name='Title (UK)'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (RU)'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_uk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (UK)'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (RU)'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_uk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (UK)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(blank=True, default='', verbose_name='Answer (RU)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uk',
            field=models.TextField(blank=True, default='', verbose_name='Answer (UK)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Question (RU)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Question (UK)'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (RU)'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_uk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (UK)'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Description (RU)'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uk',
            field=models.TextField(blank=True, default='', verbose_name='Description (UK)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (RU)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (UK)'),
        ),
        migrations.AddField(
            model_name='packets',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Description (RU)'),
        ),
        migrations.AddField(
            model_name='packets',
            name='description_uk',
            field=models.TextField(blank=True, default='', verbose_name='Description (UK)'),
        ),
        migrations.AddField(
            model_name='packets',
            name='features_text_ru',
            field=models.TextField(blank=True, default='', verbose_name='Features (RU)'),
        ),
        migrations.AddField(
            model_name='packets',
            name='features_text_uk',
            field=models.TextField(blank=True, default='', verbose_name='Features (UK)'),
        ),
        migrations.AddField(
            model_name='packets',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (RU)'),
        ),
        migrations.AddField(
            model_name='packets',
            name='title_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (UK)'),
        ),
        migrations.AddField(
            model_name='place',
            name='address_ru',
            field=models.TextField(blank=True, verbose_name='Address (RU)'),
        ),
        migrations.AddField(
            model_name='place',
            name='address_uk',
            field=models.TextField(blank=True, verbose_name='Address (UK)'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name (RU)'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name (UK)'),
        ),
        migrations.AddField(
            model_name='separately',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Description (RU)'),
        ),
        migrations.AddField(
            model_name='separately',
            name='description_uk',
            field=models.TextField(blank=True, default='', verbose_name='Description (UK)'),
        ),
        migrations.AddField(
            model_name='separately',
            name='features_text_ru',
            field=models.TextField(blank=True, default='', verbose_name='Features (RU)'),
        ),
        migrations.AddField(
            model_name='separately',
            name='features_text_uk',
            field=models.TextField(blank=True, default='', verbose_name='Features (UK)'),
        ),
        migrations.AddField(
            model_name='separately',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (RU)'),
        ),
        migrations.AddField(
            model_name='separately',
            name='title_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (UK)'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Description (RU)'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='description_uk',
            field=models.TextField(blank=True, default='', verbose_name='Description (UK)'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (RU)'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='title_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (UK)'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='message_ru',
            field=models.TextField(blank=True, default='', verbose_name='Message (RU)'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='message_uk',
            field=models.TextField(blank=True, default='', verbose_name='Message (UK)'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='subject_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subject (RU)'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='subject_uk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subject (UK)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Description (RU)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='description_uk',
            field=models.TextField(blank=True, default='', verbose_name='Description (UK)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='features_text_ru',
            field=models.TextField(blank=True, default='', verbose_name='Features (RU)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='features_text_uk',
            field=models.TextField(blank=True, default='', verbose_name='Features (UK)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (RU)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='title_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (UK)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Description (RU)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_uk',
            field=models.TextField(blank=True, default='', verbose_name='Description (UK)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='details_html_ru',
            field=models.TextField(blank=True, default='', verbose_name='Details HTML (RU)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='details_html_uk',
            field=models.TextField(blank=True, default='', verbose_name='Details HTML (UK)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='features_text_ru',
            field=models.TextField(blank=True, default='', verbose_name='Features (RU)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='features_text_uk',
            field=models.TextField(blank=True, default='', verbose_name='Features (UK)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (RU)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (UK)'),
        ),
    ]
