# Generated by Django 6.0.3 on 2026-03-07 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iprovider', '0043_category_title_ru_category_title_uk_city_name_ru_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
